### PR TITLE
YOUR MISSING H IN ASYNCHRONOUS IS PISSING ME OFF AAAAAAAAAAA

### PR DESCRIPTION
**Pull request by efwxx**

### CODE REVIEW

**Comment by efwxx** [comment]
ITS STUPID

**Comment by RealistikDash** [comment]
FJIOWESJGOIERJHRTIOGIKWESPOIGKER

**Comment by RealistikDash** [comment]
*you're :trollface:

**Comment by efwxx** [comment]
it's actually grammatically correct gfy :trollface:

**Comment by RealistikDash** [comment]
WAIT I MISREAD

**Comment by RealistikDash** [comment]
NOOOOOOOOOO

**Comment by efwxx** [comment]
L
L
L
LLLLL

**Pull request merged**
