### PR TITLE
help relesto with his existential problems with orjson

### PR DESCRIPTION
**Pull request by lenforiee**

### CODE REVIEW

**Comment by RealistikDash** [comment]
I'll really quickly test if this works

**Review by spookybear0 — APPROVED** [review]
it good

**Comment by RealistikDash** [comment]
After setting up a quick GDPyS instance I receive this issue while using your PR.
```py
Traceback (most recent call last):
  File "/tmp/GDPyS/gdpys.py", line 3, in <module>
    from config import conf
  File "/tmp/GDPyS/config.py", line 76, in <module>
    class Config(ConfigReader):
  File "/tmp/GDPyS/config.py", line 27, in __init_subclass__
    cls.__init__(cls)
  File "/tmp/GDPyS/config.py", line 22, in __init__
    self.json: JsonFile = JsonFile("config.json")
  File "/tmp/GDPyS/helpers/common.py", line 28, in __init__
    self.file = json_load(f)
orjson.JSONDecodeError: Input must be bytes, bytearray, or str: line 1 column 1 (char 0)
```

**Comment by lenforiee** [comment]
i will have look to whats happened there

**Comment by lenforiee** [comment]
ive added another changes sadly orjson.dumps dont have ablility to save to files but atleast load will work

**Comment by lenforiee** [comment]
there is possibility to fully get potential of orjson but that means we must be sure orjson will install for everyone, other wise config might lock server from even starting on

**Review by RealistikDash — APPROVED** [review]
Looks good now, checked the changes and they work as intended

**Pull request merged**
